name: boutique_shop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  flutter_slidable: ^3.1.1


  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3


  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4


  async: ^2.11.0
  shared_preferences: ^2.2.2
  http: ^1.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
